DASM_BIN_PATH=../../../dasm/bin/dasm
DASM_INCLUDE_PATH=../../../dasm/machines/atari2600/
ROM_PATH=/mnt/d/games/atari2600

ogam_jan_2016: 
	$(DASM_BIN_PATH) ogam_jan_2016.asm -s$(ROM_PATH)/ogam_jan_2016.sym -l$(ROM_PATH)/ogam_jan_2016.lst -I$(DASM_INCLUDE_PATH) -f3 -v5 -o$(ROM_PATH)/ogam_jan_2016.bin